global:
  scrape_interval:     20s
  evaluation_interval: 20s

  external_labels:
      monitor: 'cadvisor-monitor'

scrape_configs:

  - job_name: 'cadvisor-job'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['cadvisor:8080']