{
 "title": "Containers Resource Usage",
 "time": { "from": "2018-03-04T03:09:55.334Z", "to": "2018-03-04T15:09:55.334Z" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_system_seconds_total{name=~\"compose_.*\"}",
     "legendFormat": "{{name}} {{id}} {{image}}"
    },
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{name=~\"compose_.*\"}",
     "legendFormat": "{{name}} {{id}} {{image}}"
    },
    {}
   ]
  },
  {
   "title": "FS Writes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_fs_writes_total{name=~\"compose_.*\"}",
     "legendFormat": "{{device}} {{name}} {{id}} {{image}}"
    },
    {}
   ]
  }
 ]
}